### ISSUE TITLE
Data used

### ISSUE THREAD

**Issue by ThomasDelSantoONeill** [dgtaillie/python_strokes_gained#1]
Dear @dgtaillie,

May I ask where did you find these data??

Thank you very much in advance.

All the absolute best,

Thomas.

**Comment by dgtaillie** [comment]
They were taken from every shot counts, Mark Broadie:s book on strokes
gained.

**Comment by ThomasDelSantoONeill** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by ThomasDelSantoONeill** [comment]
Fantastic! Thank you for the reference, I was looking for data to generate my own R shiny app.
